/*
 * Bitcoind
 *
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * API version: 0.16
 * Contact: johan@lepetitbloc.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MemoryPool struct {
	// the number of transactions in the TX mempool
	Size int64 `json:"size,omitempty"`
	// size of the TX mempool in bytes
	Bytes int64 `json:"bytes,omitempty"`
	// total TX mempool memory usage
	Usage int64 `json:"usage,omitempty"`
	// maximum memory usage for the mempool in bytes
	Maxmempool int64 `json:"maxmempool,omitempty"`
	// minimum feerate (BTC per KB) for tx to be accepted
	Mempoolminfee float32 `json:"mempoolminfee,omitempty"`
	Minrelaytxfee float32 `json:"minrelaytxfee,omitempty"`
}
