/*
 * Bitcoind
 *
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * API version: 0.16
 * Contact: johan@lepetitbloc.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ChainInfo struct {
	// Current network name as defined in BIP70 (main, test, regtest)
	Chain string `json:"chain,omitempty"`
	// The current number of blocks processed in the server
	Blocks int64 `json:"blocks,omitempty"`
	// The current number of headers we have validated
	Headers int64 `json:"headers,omitempty"`
	// The hash of the currently best block
	Bestblockhash string `json:"bestblockhash,omitempty"`
	// The current difficulty
	Difficulty int64 `json:"difficulty,omitempty"`
	// The median time of the 11 blocks before the most recent block on the blockchain
	Mediantime int32 `json:"mediantime,omitempty"`
	// Estimate of verification progress [0..1]
	Verificationprogress int32 `json:"verificationprogress,omitempty"`
	Initialblockdownload bool `json:"initialblockdownload,omitempty"`
	// Total amount of work in active chain, in hexadecimal
	Chainwork string `json:"chainwork,omitempty"`
	SizeOnDisk int64 `json:"size_on_disk,omitempty"`
	// If the blocks are subject to pruning
	Pruned bool `json:"pruned,omitempty"`
	// status of softforks in progress
	Softforks []Bip `json:"softforks,omitempty"`
	Bip9Softforks *ChainInfoBip9Softforks `json:"bip9_softforks,omitempty"`
	// An eventual warning on the current build status.
	Warnings string `json:"warnings,omitempty"`
}
