/*
 * Bitcoind
 *
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * API version: 0.16
 * Contact: johan@lepetitbloc.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Transaction struct {
	// The transaction amount in BTC
	Amount float32 `json:"amount,omitempty"`
	// The amount of the fee in BTC. This is negative and only available for the send category of transactions.
	Fee float32 `json:"fee,omitempty"`
	// The number of confirmations
	Confirmations int64 `json:"confirmations,omitempty"`
	// The block hash
	Blockhash string `json:"blockhash,omitempty"`
	// The index of the transaction in the block that includes it
	Blockindex int64 `json:"blockindex,omitempty"`
	// The time in seconds since epoch (1 Jan 1970 GMT)
	Blocktime int32 `json:"blocktime,omitempty"`
	// The transaction id
	Txid string `json:"txid,omitempty"`
	// The transaction hash
	Txhash string `json:"txhash,omitempty"`
	Version int32 `json:"version,omitempty"`
	Size int32 `json:"size,omitempty"`
	Vsize int32 `json:"vsize,omitempty"`
	Locktime int32 `json:"locktime,omitempty"`
	// The transaction time in seconds since epoch (1 Jan 1970 GMT)
	Time int32 `json:"time,omitempty"`
	// The time received in seconds since epoch (1 Jan 1970 GMT)
	Timereceived int32 `json:"timereceived,omitempty"`
	// Whether this transaction could be replaced due to BIP125 (replace-by-fee); may be unknown for unconfirmed transactions not in the mempool
	Bip125Replaceable string `json:"bip125-replaceable,omitempty"`
}
