/*
 * Bitcoind
 *
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * API version: 0.16
 * Contact: johan@lepetitbloc.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Bip9 struct {
	Status string `json:"status,omitempty"`
	// The starttime specifies a minimum median time past of a block at which the bit gains its meaning.
	StartTime int64 `json:"startTime,omitempty"`
	// The timeout specifies a time at which the deployment is considered failed. If the median time past of a block >= timeout and the soft fork has not yet locked in (including this block's bit state), the deployment is considered failed on all descendants of the block.
	Timeout int64 `json:"timeout,omitempty"`
	Since int64 `json:"since,omitempty"`
}
